[languages.es]
  title = "Fcch Blog | Apuntes, guías y recordatorios"
  label = "Spanish"
  weight = 1
  
[languages.en]
  title = "Fcch Blog | Notes, guides and reminders"
  label = "English"
  weight = 2
 