[es]
  title = "Fcch Blog | Apuntes, guías y recordatorios"
  LanguageName = "Spanish"
  weight = 1
  
[en]
  title = "Fcch Blog | Notes, guides and reminders"
  LanguageName = "English"
  weight = 2
 