twitter = "@fcchbo"
largeTwitterCard = false
introDescription = "Perpetual student, technologist, computer security enthusiast, free software, open source, Fedorian }:)."
# introURL = "about/"
# description = ""
# showShare = false

# Google analytics Id
ga_analytics = "UA-154973733-1"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 20

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = false

# directory(s) where your articles are located
mainSections = ["post"]

# center logo on navbar
centerLogo = false 
logo = "logos/logo.png"

# Label Non inline images on an article body
figurePositionShow = false
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure"

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left"

enforceLightMode = false
# enforceDarkMode = false

# customize footer icon. see issue https://github.com/chipzoller/hugo-clarity/issues/77
# footerLogo = "icons/copy.svg"

# Text for the languages menu.
languageMenuName = "🌐"

# Title separator, default to |.
# titleSeparator = "|"

# Enable or disable comments globally. Default to true.
# comments = false

# Maximum number of recent posts.
# numberOfRecentPosts = 8

# Maximum number of featured posts.
# numberOfFeaturedPosts = 8

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
# dateFormat = "2006-01-02" # Default to "Jan 2, 2006".
# customFonts = false # toggle to true if you want to use custom fonts only.

# The year when ths website was created, this value is used in the copyright
# notice of the footer.
# since = 2016
iconsDir = "icons/"

# website author
[author]
name = "Fcch"
# photo = "images/jane-doe.png"

[plausible_analytics]
enable = false
websiteDomain = "fcch.xyz"
