[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "GNU/Linux"
  url = "post/gnu-linux/"
  weight = -109

[[main]]
  name = "Infrastructure"
  url = "post/infrastructure/"
  weight = -108

[[main]]
  name = "Web"
  url = "post/web/"
  weight = -107

[[main]]
  name = "Cloud"
  url = "post/cloud/"
  weight = -106

[[main]]
  name = "About me"
  url = "about/"
  weight = -105

# social menu links
[[social]]
  name = "twitter"
  type = "social"
  weight = 1
  url = "https://twitter.com/fcchbo"
[[social]]
  name = "instagram"
  weight = 2
  url = "https://instagram.com/fcchbo"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/freddy-fcch/"
[[social]]
  name = "github"
  weight = 4
  url = "https://github.com/fcchn4"
[[social]]
  name = "gitlab"
  weight = 5
  url = "https://gitlab.com/fcch"
[[social]]
  name = "rss"
  weight = 6
  url = "index.xml"
