[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links
[[social]]
  name = "twitter"
  type = "social"
  weight = 1
  url = "https://twitter.com/fcchbo"
[[social]]
  name = "instagram"
  weight = 2
  url = "https://instagram.com/fcchbo"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/freddy-fcch/"
[[social]]
  name = "github"
  weight = 4
  url = "https://github.com/fcchn4"
[[social]]
  name = "gitlab"
  weight = 5
  url = "https://gitlab.com/fcch"
[[social]]
  name = "rss"
  weight = 6
  url = "index.xml"
